import { h, getElementStyle } from './../utils';
const iconsClassName = "material-icons";
export const add = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'add');
export const addG = h('i',{ className: "icons-g", style: getElementStyle('icon') },'add');
export const addR = h('i',{ className: "icons-r", style: getElementStyle('icon') },'add');
export const trash = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'delete_outlined');
export const menu = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'more_horiz');
export const hide = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'visibility_off');
export const show = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'minimize');
export const normalview = h('i',{ className: iconsClassName, style: getElementStyle('icon') },'widgets');
